# Site settings
title: MitchMania Labs
baseurl: ""
url: "http://mitchmania.com"
twitter: mitchmania
github:  mitchmania
permalink: /:categories/:title/
analyticsEnabled: true

# Build settings
markdown: kramdown
highlighter: pygments

collections:
  authors:
  projects:

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
